### ISSUE TITLE
The color of the station is not correct(Oculus version)

### ISSUE THREAD

**Issue by smallelephant9516** [CryoVR/CryoVR_GridClipping#1]
![com CryoVR Autogrid_Clipping-20211201-220723](https://user-images.githubusercontent.com/52638056/144352861-37bf02bc-2ec9-43e3-a0cd-c90489fab2d4.jpg)
The color of the station should be white instead of grey

**Comment by Wandayu** [comment]
This may be because of the light build, and will be repaired in the next version
