### ISSUE TITLE
Text guidance is step 3 is confusing. 

### ISSUE THREAD

**Issue by smallelephant9516** [CryoVR/CryoVR_GridClipping#10]
The text guidance in step 3 is very confusing, I don't quite understand the last sentence. 
![image](https://user-images.githubusercontent.com/52638056/101427730-6b9f8680-38cd-11eb-82ed-8c0d5b7a5ec3.png)

**Comment by Wandayu** [comment]
In version 1.02, we have remade all the instruction text sentences which are more detailed
