### ISSUE TITLE
How to quit the game? 

### ISSUE THREAD

**Issue by chenyingjie** [CryoVR/CryoVR_GridClipping#14]
Maybe we need a quit button?

**Comment by Wandayu** [comment]
In version 1.04, we will add a menu bar to let users go back to the main menu / quit the game.
![v1 04_MenuinGame](https://user-images.githubusercontent.com/31882005/102843323-f658a900-43d6-11eb-910f-d1b6349bbc83.png)

**Comment by smallelephant9516** [comment]
There is a quit game button
