### ISSUE TITLE
distance of tweezer to the pen shape device

### ISSUE THREAD

**Issue by chenyingjie** [CryoVR/CryoVR_GridClipping#19]
While I transfer the ring from the tweezer to the pen tip, the ring automatically jump to pen when the distance is about 1cm. These two objects (tweezer and pen) should touch each other to finish the transfer.

**Comment by Wandayu** [comment]
In version 1.04, we have adjusted the position of collision box, so that these two things need to touch each other to finish the transfer.

**Comment by smallelephant9516** [comment]
I think this has been fixed in the newest version
