### ISSUE TITLE
The height of the table is too low

### ISSUE THREAD

**Issue by smallelephant9516** [CryoVR/CryoVR_GridClipping#2]
The height of the table is too high, then, we need to reach under our table in a real environment. And it will block the connection between the controller and tracker. We hope the height of the table in the VR environment to be 6 inches (15cm) higher than current setting.

**Comment by Wandayu** [comment]
In version 1.01, we lowered the camera's height reference position so that the entire tabletop moves upward.

![Table Height](https://user-images.githubusercontent.com/31882005/101402194-6fb5af00-38a1-11eb-9853-4d13502aba1f.png)

**Comment by smallelephant9516** [comment]
Sorry for reopen this issue again, as I try it in my home instead of lab today, the table seems still to low, so maybe it is a better idea to make it even lower.

**Comment by smallelephant9516** [comment]
In this figure, my hand already touch the table
![image](https://user-images.githubusercontent.com/52638056/102156060-bdef2300-3e4a-11eb-8a3a-f2e899029c3c.png)
