### ISSUE TITLE
Highlighting for the tool to take the transparent lid

### ISSUE THREAD

**Issue by smallelephant9516** [CryoVR/CryoVR_GridClipping#3]
In the step of cooling down the transparent lid, we need to use a specific tool to attach the transparent lid. The tool that is used to attach the transparent lid to the clipped grid box is not highlighted, so the user does not know which tool to use.

**Comment by Wandayu** [comment]
In version 1.00, there are two separate steps. The first step is to pick up the transparent lid, followed by the second step of picking up the tool and attaching the lid to the tool. In the first step, the system highlights and indicates the lid, but only after the second step is completed does the system indicate the location of the tool.


![Tool for Transparent Lid](https://user-images.githubusercontent.com/31882005/101403293-05057300-38a3-11eb-8bf9-6781e75ac448.png)

**Comment by Wandayu** [comment]
In verion 1.02, we make these two UI both appear in the first step picking up the lid so that the users can have an overview of how to attach the transparent lid.

 
![v1 02_StorageBoxTool](https://user-images.githubusercontent.com/31882005/101672926-7882be00-3a24-11eb-9fd4-f6c59f89b7e7.png)

**Comment by smallelephant9516** [comment]
It is clearly indicated
