### ISSUE TITLE
Indicating the step number of each step on the white board

### ISSUE THREAD

**Issue by smallelephant9516** [CryoVR/CryoVR_GridClipping#5]
We want the specific step numbers to be shown on the whiteboard on each step. We hope this could be done for all the modules in the CryoVR

**Comment by Wandayu** [comment]
This feature has been implemented in version 1.01 and is ready for testing

![Task Procedure](https://user-images.githubusercontent.com/31882005/101401725-bbb42400-38a0-11eb-8d33-646fe81d6f59.png)

**Comment by smallelephant9516** [comment]
The steps should start from 1 instead of 0
![image](https://user-images.githubusercontent.com/52638056/101427291-9b01c380-38cc-11eb-81b0-876449bf23a5.png)

**Comment by Wandayu** [comment]
While you're doing this, you haven't done any of the steps yet, so it's 0. The first number represents the number of steps you have completed.

**Comment by Wandayu** [comment]
In version 1.02, we have let the first number represent the index of current step. So it starts from 1.

![v1 02_InstuctionBoardIndex](https://user-images.githubusercontent.com/31882005/101673865-b7654380-3a25-11eb-8873-1171a29b1017.png)

**Comment by smallelephant9516** [comment]
Probably cancel the step number in the prologue 
![image](https://user-images.githubusercontent.com/52638056/102155831-520cba80-3e4a-11eb-998b-7a2cdcf5bb2f.png)

**Comment by Wandayu** [comment]
In version 1.03, the step number in the prologue has been deleted
