### ISSUE TITLE
Additional information for identifying the direction of the clip ring

### ISSUE THREAD

**Issue by smallelephant9516** [CryoVR/CryoVR_GridClipping#7]
There should be an additional step for identifying the face of the clip ring, which the smooth side should on the top.

**Comment by Wandayu** [comment]
In version 1.02, we have temporarily placed an instuction board to show the details of the face of the clip ring. But we may have more details about this step in later version.

![v1 02_InstructionBoard](https://user-images.githubusercontent.com/31882005/101673485-38700b00-3a25-11eb-85c8-272d6e3fb5e2.png)

**Comment by smallelephant9516** [comment]
I think this is clearly indicated.
