### ISSUE TITLE
The operation of the pushing the clip tool should be one hand. 

### ISSUE THREAD

**Issue by smallelephant9516** [CryoVR/CryoVR_GridClipping#8]
The operation of pushing the clip tool should be done by one hand with the thumb. currently, I need to use another hand to touch the top of the clip tool or the highlighting will not disappear in step 3 and 18
![image](https://user-images.githubusercontent.com/52638056/101427530-0e0b3a00-38cd-11eb-9111-ed81f91a35be.png)

**Comment by Wandayu** [comment]
I think it is the same problem with #6
